language: objective-c
before_install:
  - brew update
  - brew reinstall xctool
  - gem update cocoapods
xcode_workspace: BFPaperButton.xcworkspace
xcode_scheme: BFPaperButton
xcode_sdk:
  - iphonesimulator7.0
  - iphonesimulator7.1